### PR TITLE
Feature: Map Rotation

### PR DESCRIPTION
**Pull request by itho**
I found myself wanting to rotate a map today to share ahead of a game, and figured it might be fun to add the functionality to the site! Thanks for making this open-sourced!

I know there are some more dynamic ways to rotate the arrays, but with a maximum of 4 rings that I could see, I didn't think it was worth the added complexity and brain power. 😅

I did have a quick look through the rest of the source, and I'm hoping I haven't missed anything (e.g., URL updates, etc.). Currently, the player positions/names don't rotate with the board, but I'm sure that wouldn't be too much effort to add if that was preferred.

Edit: I did have to do some `npm audit fix`'ing to get the repo working on my local machine, but I haven't committed any of these updates.

### CODE REVIEW

**Comment by itho** [comment]
I've just realised that this does not play nicely with hyperlanes, which would need rotating to maintain the correct connections.

**Comment by KeeganW** [comment]
Thanks @itho ! I added some tooltips, but otherwise looks good! I agree, could do something fancy with rotating tiles dynamically, but its probably not worth the headache, just like it wasn't worth it for the original map building 😅 

Thank you for your contribution!

**Comment by KeeganW** [comment]
Just deployed, should be visible on the main site. Thanks again @itho!

**Comment by itho** [comment]
You're welcome, thank you for the site!

**Pull request merged**
